# Generated by Django 4.2.6 on 2024-02-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Templates',
        ),
    ]
