# Generated by Django 4.2.6 on 2024-02-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing_page', '0002_delete_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain template', models.FileField(upload_to='templates/')),
                ('template', models.FileField(upload_to='templates/')),
            ],
        ),
    ]
