# Generated by Django 4.1.7 on 2024-02-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_uploadedfile_extractedemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ectracted_Resume_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first_name', max_length=100)),
                ('middle_name', models.CharField(default='middle_name', max_length=100)),
                ('last_name', models.CharField(default='last_name', max_length=100)),
                ('skills', models.CharField(default='skills', max_length=500)),
                ('internships', models.CharField(default='internships', max_length=9000)),
                ('experience', models.CharField(default='exp', max_length=9000)),
                ('education', models.CharField(default='education', max_length=3000)),
                ('langauges', models.CharField(default='English', max_length=2000)),
                ('projects', models.CharField(default='project', max_length=9000)),
                ('UploadedFile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.uploadedfile')),
            ],
        ),
    ]
