# Generated by Django 4.1.7 on 2024-02-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0007_ectracted_resume_details_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedemail',
            name='uploaded_file',
        ),
        migrations.DeleteModel(
            name='Ectracted_Resume_Details',
        ),
        migrations.DeleteModel(
            name='ExtractedEmail',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
